web_server_location       = "Westus2"
web_server_rg             = "web-rg"
Web_server_address_space  = "web-server"
Address_prefix            =  "1.0.0.0/22"
web_server_address_prefix = "1.0.1.0/24"
web_server_name           = "web-01"
environments              = "development"